version: '3'
services:
  mysql:
    image: mysql:8.0
    ports:
      - "13306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=dami
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=market
    volumes:
      - ./data/mysql/:/var/lib/mysql

networks:
  default:
    driver: bridge
